# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # This ensures we get the full commit history

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'
          cache: maven

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Get current time
        id: time
        run: echo "time=$(date +'%H:%M:%S')" >> $GITHUB_OUTPUT

      - name: Get current commit
        id: commit
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build with Maven and measure time
        id: build
        run: |
          start_time=$(date +%s)
          mvn --batch-mode --update-snapshots verify
          end_time=$(date +%s)
          build_time=$((end_time - start_time))
          echo "build_time=$build_time" >> $GITHUB_OUTPUT

      - name: Update metrics data
        # if: github.ref == 'refs/heads/master'
        run: |
          # Ensure docs directory exists
          mkdir -p docs

          # Set file path
          BUILD_TIMES_CSV="docs/build-times.csv"
          CYCLES_WITHOUT_TESTS_CSV="docs/cycles-without-tests.csv"
          CYCLES_WITH_TESTS_CSV="docs/cycles-with-tests.csv"
          JSON_FILE="use-core/cycles-tests-results.json"

          # Update build times data
          if [ ! -f "$BUILD_TIMES_CSV" ]; then
            echo "date,time,commit,buildtime" > "$BUILD_TIMES_CSV"
          fi

          # Debug outputs to see what values we're getting
#          echo "Date: ${{ steps.date.outputs.date }}"
#          echo "Time: ${{ steps.time.outputs.time }}"
#          echo "Commit: ${{ steps.commit.outputs.sha }}"
#          echo "Build time: ${{ steps.build.outputs.build_time }}"

          # Append the new build time data
          echo "${{ steps.date.outputs.date }},${{ steps.time.outputs.time }},${{ steps.commit.outputs.sha }},${{ steps.build.outputs.build_time }}" >> "$BUILD_TIMES_CSV"

          # Process cycle dependency results if JSON file exists
          if [ -f "$JSON_FILE" ]; then
            # Create CSV header if file doesn't exist
            if [ ! -f "$CYCLES_WITHOUT_TESTS_CSV" ]; then
              echo "date,time,commit,all_modules,analysis,api,config,gen,graph,main,parser,uml,util" > "$CYCLES_WITHOUT_TESTS_CSV"
            fi
            if [ ! -f "$CYCLES_WITH_TESTS_CSV" ]; then
              echo "date,time,commit,all_modules,analysis,api,config,gen,graph,main,parser,uml,util" > "$CYCLES_WITH_TESTS_CSV"
            fi

            # Extract values from JSON using jq
            ALL_MODULES_NO_TESTS=$(jq -r '.without_tests.all_modules // 0' "$JSON_FILE")
            ANALYSIS_NO_TESTS=$(jq -r '.without_tests.analysis // 0' "$JSON_FILE")
            API_NO_TESTS=$(jq -r '.without_tests.api // 0' "$JSON_FILE")
            CONFIG_NO_TESTS=$(jq -r '.without_tests.config // 0' "$JSON_FILE")
            GEN_NO_TESTS=$(jq -r '.without_tests.gen // 0' "$JSON_FILE")
            GRAPH_NO_TESTS=$(jq -r '.without_tests.graph // 0' "$JSON_FILE")
            MAIN_NO_TESTS=$(jq -r '.without_tests.main // 0' "$JSON_FILE")
            PARSER_NO_TESTS=$(jq -r '.without_tests.parser // 0' "$JSON_FILE")
            UML_NO_TESTS=$(jq -r '.without_tests.uml // 0' "$JSON_FILE")
            UTIL_NO_TESTS=$(jq -r '.without_tests.util // 0' "$JSON_FILE")

            ALL_MODULES_WITH_TESTS=$(jq -r '.with_tests.all_modules // 0' "$JSON_FILE")
            ANALYSIS_WITH_TESTS=$(jq -r '.with_tests.analysis // 0' "$JSON_FILE")
            API_WITH_TESTS=$(jq -r '.with_tests.api // 0' "$JSON_FILE")
            CONFIG_WITH_TESTS=$(jq -r '.with_tests.config // 0' "$JSON_FILE")
            GEN_WITH_TESTS=$(jq -r '.with_tests.gen // 0' "$JSON_FILE")
            GRAPH_WITH_TESTS=$(jq -r '.with_tests.graph // 0' "$JSON_FILE")
            MAIN_WITH_TESTS=$(jq -r '.with_tests.main // 0' "$JSON_FILE")
            PARSER_WITH_TESTS=$(jq -r '.with_tests.parser // 0' "$JSON_FILE")
            UML_WITH_TESTS=$(jq -r '.with_tests.uml // 0' "$JSON_FILE")
            UTIL_WITH_TESTS=$(jq -r '.with_tests.util // 0' "$JSON_FILE")

            # Append new row to CSVs
            echo "${{ steps.date.outputs.date }},${{ steps.time.outputs.time }},${{ steps.commit.outputs.sha }},$ALL_MODULES_NO_TESTS,$ANALYSIS_NO_TESTS,$API_NO_TESTS,$CONFIG_NO_TESTS,$GEN_NO_TESTS,$GRAPH_NO_TESTS,$MAIN_NO_TESTS,$PARSER_NO_TESTS,$UML_NO_TESTS,$UTIL_NO_TESTS" >> "$CYCLES_WITHOUT_TESTS_CSV"
            echo "${{ steps.date.outputs.date }},${{ steps.time.outputs.time }},${{ steps.commit.outputs.sha }},$ALL_MODULES_WITH_TESTS,$ANALYSIS_WITH_TESTS,$API_WITH_TESTS,$CONFIG_WITH_TESTS,$GEN_WITH_TESTS,$GRAPH_WITH_TESTS,$MAIN_WITH_TESTS,$PARSER_WITH_TESTS,$UML_WITH_TESTS,$UTIL_WITH_TESTS" >> "$CYCLES_WITH_TESTS_CSV"

            echo "Updated cycle dependency data in $CYCLES_WITHOUT_TESTS_CSV and $CYCLES_WITH_TESTS_CSV"
          else
            echo "Warning: JSON file with cycle dependency results not found at $JSON_FILE"
          fi

          # Configure Git
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          # Commit and push the updated CSV files
          git add docs/
          git commit -m "Update metrics data [skip ci]" || echo "No changes to commit"
          git push

      - name: Upload build result
        run: mkdir staging && cp use-assembly/target/*.zip staging

      - uses: actions/upload-artifact@v4
        with:
          name: Package
          path: staging
