name: Java CI with Maven
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots verify | tee build_output.log
    - name: Upload build result
      run: mkdir staging && cp use-assembly/target/*.zip staging
    - uses: actions/upload-artifact@v4
      with:
        name: Package
        path: staging
    - uses: actions/upload-artifact@v4
      with: 
        name: build-log
        path: build_output.log
