# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # This ensures we get the full commit history
    
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'adopt'
        cache: maven
    
    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d')"
    
    - name: Get current time
      id: time
      run: echo "time=$(date +'%H:%M:%S')"
    
    - name: Get current commit
      id: commit
      run: echo "sha=$(git rev-parse --short HEAD)"
    
    - name: Build with Maven and measure time
      id: build
      run: |
        start_time=$(date +%s)
        mvn --batch-mode --update-snapshots verify
        end_time=$(date +%s)
        build_time=$((end_time - start_time))
        echo "build_time=$build_time"
    
    - name: Update build time data
      # if: github.ref == 'refs/heads/master'
      run: |
        # Check if file exists, create if it doesn't
        if [ ! -f build-times.csv ]; then
          echo "date,time,commit,buildtime" > build-times.csv
        fi
        
        # Append the new build time data
        echo "${{ steps.date.outputs.date }},${{ steps.time.outputs.time }},${{ steps.commit.outputs.sha }},${{ steps.build.outputs.build_time }}" >> build-times.csv
        
        # Configure Git
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Commit and push the updated CSV
        git add build-times.csv
        git commit -m "Update build time data [skip ci]" || echo "No changes to commit"
        git push
    
    - name: Upload build result
      run: mkdir staging && cp use-assembly/target/*.zip staging
    
    - uses: actions/upload-artifact@v4
      with:
        name: Package
        path: staging
